spring:
  application:
    name: FuteLove
  datasource:
    url: jdbc:mariadb://localhost:3306/futelove?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

google:
  cloud:
    connection-timeout: 60000
    read-timeout: 60000
    security-key-file: rising-daylight-435322-s8-c6f36cea5e36.json
    bucketName: fute-love-media

opencv:
  haarcascades-path: classpath:opencv/haarcascades/haarcascade_frontalface_alt.xml
  show-video: true